# Generated by Django 6.0.6 on 2026-07-25 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_deadline_alter_task_importance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nombre corto para identificar el snippet', max_length=100)),
                ('content', models.TextField(help_text='Texto del comentario. Usa {student_name} para personalizar.')),
                ('category', models.CharField(blank=True, help_text='Categoría: elogio, mejora, instrucción, etc.', max_length=50)),
                ('is_shared', models.BooleanField(default=False, help_text='Visible para otros profesores del mismo curso')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='corrected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='corrected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrected_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Puntuación 0-100', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_REVIEW', 'En revisión'), ('CORRECTED', 'Corregida'), ('RETURNED', 'Devuelta')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_by', 'status'], name='idx_task_by_status'),
        ),
        migrations.AddField(
            model_name='commentsnippet',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_snippets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='commentsnippet',
            unique_together={('teacher', 'title')},
        ),
    ]
