# Generated by Django 6.0.6 on 2026-07-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options_user_unique_email_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='meta_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'meta_key'], name='idx_notif_user_meta'),
        ),
    ]
