# Generated by Django 6.0.6 on 2026-07-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_notification_meta_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Estudiante'), ('TEACHER', 'Profesor'), ('STAFF', 'Personal'), ('PROGRAMMER', 'Programador'), ('ADMIN', 'Administrador')], db_index=True, default='STUDENT', max_length=20),
        ),
    ]
