# Generated by Django 6.0.6 on 2026-07-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='badges',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='xp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Estudiante'), ('TEACHER', 'Profesor'), ('STAFF', 'Personal'), ('PROGRAMMER', 'Programador'), ('ADMIN', 'Administrador'), ('SCHOOL_ADMIN', 'Administrador Escolar / UTP')], db_index=True, default='STUDENT', max_length=20),
        ),
    ]
