# Generated by Django 6.0.6 on 2026-07-26 02:58

from django.db import migrations, models


def migrate_admin_to_teacher(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.filter(role__in=['ADMIN', 'SCHOOL_ADMIN']).update(role='TEACHER')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_avatar_user_badges_user_level_user_xp_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_admin_to_teacher, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Estudiante'), ('TEACHER', 'Profesor'), ('STAFF', 'Personal'), ('PROGRAMMER', 'Programador')], db_index=True, default='STUDENT', max_length=20),
        ),
    ]
