# Generated by Django 6.0.6 on 2026-08-11 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pending_email',
            field=models.EmailField(blank=True, help_text='Email nuevo esperando confirmación de cambio.', max_length=254, null=True),
        ),
        migrations.CreateModel(
            name='NotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_deadlines', models.BooleanField(default=True, help_text='Recordatorios de vencimiento de tareas por email.')),
                ('in_app', models.BooleanField(default=True, help_text='Notificaciones in-app de vencimientos y hábitos.')),
                ('push', models.BooleanField(default=True, help_text='Alertas push del navegador.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
