# Generated by Django 6.0.6 on 2026-07-26 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('EASY', 'Fácil'), ('MEDIUM', 'Medio'), ('HARD', 'Difícil')], max_length=12)),
                ('category', models.CharField(choices=[('REFACTORING', 'Refactoring'), ('SQL_OPTIMIZATION', 'Optimización SQL'), ('SECURITY_OWASP', 'Seguridad OWASP'), ('ARCHITECTURE', 'Arquitectura')], max_length=20)),
                ('initial_code', models.TextField(blank=True, default='')),
                ('test_cases', models.JSONField(default=list)),
                ('xp_reward', models.PositiveIntegerField(default=25)),
                ('frequency', models.CharField(choices=[('DAILY', 'Diario'), ('EVERY_3_DAYS', 'Cada 3 días'), ('WEEKLY', 'Semanal')], default='DAILY', max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DevLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('HEALTHY', 'Saludable'), ('DEGRADED', 'Degradado'), ('DOWN', 'Caído')], max_length=10)),
                ('response_time_ms', models.PositiveIntegerField(default=0)),
                ('logs_trace', models.TextField(blank=True, default='')),
                ('endpoint', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dev Log',
                'verbose_name_plural': 'Dev Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DevPingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=200)),
                ('status_code', models.PositiveIntegerField()),
                ('response_time_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DevADR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('context', models.TextField(help_text='Contexto del problema')),
                ('decision', models.TextField(help_text='Decisión tomada')),
                ('consequences', models.TextField(help_text='Consecuencias de la decisión')),
                ('status', models.CharField(choices=[('PROPOSED', 'Propuesto'), ('ACCEPTED', 'Aceptado'), ('DEPRECATED', 'Deprecado')], default='PROPOSED', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dev_adrs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ADR',
                'verbose_name_plural': 'ADRs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DevProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_handle', models.CharField(blank=True, default='', max_length=100)),
                ('preferred_stack', models.JSONField(blank=True, default=list)),
                ('total_dev_xp', models.PositiveIntegerField(default=0)),
                ('current_dev_level', models.PositiveIntegerField(default=1)),
                ('focus_mode_active', models.BooleanField(default=False)),
                ('api_token', models.CharField(blank=True, default='', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dev_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dev Profile',
                'verbose_name_plural': 'Dev Profiles',
            },
        ),
        migrations.CreateModel(
            name='DevSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('code', models.TextField()),
                ('language', models.CharField(blank=True, default='python', max_length=50)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_private', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dev_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to='dev.devprofile')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DevSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_code', models.TextField()),
                ('execution_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('memory_used_kb', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PASSED', 'Aprobado'), ('FAILED', 'Falló'), ('ERROR', 'Error')], max_length=8)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='dev.devchallenge')),
                ('dev_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='dev.devprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('dev_profile', 'challenge')},
            },
        ),
    ]
