# Generated by Django 6.0.6 on 2026-08-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habitcompletion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='category',
            field=models.CharField(choices=[('FOCUS', 'Enfoque'), ('ESSENTIAL', 'Esencial'), ('URGENT', 'Urgente'), ('WELLNESS', 'Bienestar')], db_index=True, default='ESSENTIAL', max_length=20),
        ),
    ]
