# Generated by Django 6.0.6 on 2026-07-25 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('ACADEMIC', 'Académica'), ('SOCIAL', 'Social'), ('CONSISTENCY', 'Constancia'), ('ACHIEVEMENT', 'Logro'), ('SPECIAL', 'Especial')], default='ACHIEVEMENT', max_length=20)),
                ('icon', models.CharField(default='bi-award', help_text='Icono Bootstrap Icons', max_length=50)),
                ('color', models.CharField(default='gold', help_text='Color CSS o clase', max_length=20)),
                ('xp_reward', models.PositiveIntegerField(default=0, help_text='XP extra al ganarla')),
                ('is_secret', models.BooleanField(default=False, help_text='No visible hasta ganarla')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('xp_reward', models.PositiveIntegerField(default=10, help_text='XP al completar con nota mínima')),
                ('passing_score', models.PositiveIntegerField(default=60, help_text='Nota mínima para aprobar (0-100)')),
                ('time_limit', models.PositiveIntegerField(default=0, help_text='Límite en minutos (0 = sin límite)')),
                ('max_attempts', models.PositiveIntegerField(default=3, help_text='Máx. intentos permitidos')),
                ('shuffle_questions', models.BooleanField(default=True)),
                ('shuffle_choices', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('available_from', models.DateTimeField(blank=True, null=True)),
                ('available_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.course')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('text', models.TextField()),
                ('type', models.CharField(choices=[('SINGLE', 'Opción única'), ('MULTIPLE', 'Opción múltiple'), ('TF', 'Verdadero/Falso')], default='SINGLE', max_length=10)),
                ('points', models.PositiveIntegerField(default=1)),
                ('explanation', models.TextField(blank=True, help_text='Explicación mostrada tras responder')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='gamification.quiz')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuizChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='gamification.quizquestion')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('EXTENSION', 'Día extra de plazo'), ('SKIP_TASK', 'Saltar una tarea'), ('BONUS_XP', 'Bonus XP extra'), ('BADGE', 'Badge exclusivo'), ('PRIVILEGE', 'Privilegio especial'), ('CUSTOM', 'Personalizada')], default='CUSTOM', max_length=20)),
                ('xp_cost', models.PositiveIntegerField(help_text='Costo en XP del estudiante')),
                ('icon', models.CharField(default='bi-gift', help_text='Icono Bootstrap Icons', max_length=50)),
                ('max_claims', models.PositiveIntegerField(default=0, help_text='0 = ilimitado')),
                ('current_claims', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='courses.course')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['xp_cost', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudentReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('xp_spent', models.PositiveIntegerField()),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_claims', to='gamification.reward')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claimed_rewards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-claimed_at'],
            },
        ),
        migrations.CreateModel(
            name='TipTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp_amount', models.PositiveIntegerField(default=5, help_text='XP otorgado (default 5)')),
                ('reason', models.CharField(choices=[('PARTICIPATION', 'Gran participación'), ('HELP_PEER', 'Ayudó a compañero'), ('CREATIVE', 'Solución creativa'), ('EFFORT', 'Esfuerzo extra'), ('LEADERSHIP', 'Liderazgo'), ('CUSTOM', 'Otro')], default='CUSTOM', max_length=20)),
                ('custom_reason', models.CharField(blank=True, help_text='Motivo personalizado', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tip_transactions', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips_received', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'En progreso'), ('SUBMITTED', 'Enviado'), ('GRADED', 'Calificado')], default='IN_PROGRESS', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje 0-100', max_digits=5, null=True)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('answers', models.JSONField(default=dict, help_text='Respuestas: {question_id: [choice_ids]}')),
                ('time_spent', models.PositiveIntegerField(default=0, help_text='Segundos')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='gamification.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'unique_together': {('quiz', 'student')},
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('WEEKLY', 'Semanal'), ('MONTHLY', 'Mensual')], default='WEEKLY', max_length=10)),
                ('position', models.PositiveIntegerField(help_text='Posición en el ranking')),
                ('xp_earned', models.PositiveIntegerField(default=0, help_text='XP ganado en el período')),
                ('total_xp', models.PositiveIntegerField(default=0, help_text='XP acumulado total')),
                ('tasks_completed', models.PositiveIntegerField(default=0)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['period', 'position'],
                'unique_together': {('course', 'student', 'period', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='StudentBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('xp_awarded', models.PositiveIntegerField(default=0)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_badges', to='gamification.badge')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_badges', to='courses.course')),
                ('earned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badges_awarded', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
                'unique_together': {('student', 'badge', 'course')},
            },
        ),
    ]
