# Generated by Django 6.0.6 on 2026-07-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_scheduleentry_course_tutoringslot_risktrafficlight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleentry',
            name='day',
            field=models.CharField(choices=[('MON', 'Lunes'), ('TUE', 'Martes'), ('WED', 'Miércoles'), ('THU', 'Jueves'), ('FRI', 'Viernes'), ('SAT', 'Sábado')], max_length=3),
        ),
        migrations.AlterField(
            model_name='tutoringslot',
            name='day',
            field=models.CharField(choices=[('MON', 'Lunes'), ('TUE', 'Martes'), ('WED', 'Miércoles'), ('THU', 'Jueves'), ('FRI', 'Viernes'), ('SAT', 'Sábado')], max_length=3),
        ),
    ]
